name: chicken_game
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: 3.0.5

dependencies:
  bloc: ^8.1.0
  equatable: ^2.0.3
  flame: ^1.2.1
  flame_behaviors: ^0.1.1
  flame_tiled: ^1.7.1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  flutter_localizations:
    sdk: flutter
  freezed_annotation: ^2.1.0
  get_it: ^7.2.0
  intl: ^0.17.0

dev_dependencies:
  bloc_test: ^9.0.3
  build_runner: ^2.2.0
  flame_test: ^1.6.0
  flutter_test:
    sdk: flutter
  freezed: ^2.1.0+1
  mocktail: ^0.3.0
  very_good_analysis: ^3.0.1

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/
    - assets/images/world/
    - assets/tiles/
